package br.com.indra.treinamento.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-17T16:28:58.124-03:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "EmployeeImplService",
                  wsdlLocation = "file:/C:/Users/lcastros/AppData/Local/Temp/tempdir2855332694738683493.tmp/employee_1.wsdl",
                  targetNamespace = "http://model.treinamento.indra.com.br/")
public class EmployeeImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://model.treinamento.indra.com.br/", "EmployeeImplService");
    public final static QName EmployeeImplPort = new QName("http://model.treinamento.indra.com.br/", "EmployeeImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/lcastros/AppData/Local/Temp/tempdir2855332694738683493.tmp/employee_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/lcastros/AppData/Local/Temp/tempdir2855332694738683493.tmp/employee_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmployeeImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmployeeInterface
     */
    @WebEndpoint(name = "EmployeeImplPort")
    public EmployeeInterface getEmployeeImplPort() {
        return super.getPort(EmployeeImplPort, EmployeeInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeInterface
     */
    @WebEndpoint(name = "EmployeeImplPort")
    public EmployeeInterface getEmployeeImplPort(WebServiceFeature... features) {
        return super.getPort(EmployeeImplPort, EmployeeInterface.class, features);
    }

}
